name: CMakeTest

on:
  push:
    branches: [ task6 ]
  pull_request:
    branches: [ task6 ]

#env: 
  #GOOGLE_TEST_DIR: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: ls
